[package]
name = "aho_corasearch_nif"
version = "0.1.0"
authors = ["Peter Richards"]
edition = "2021"

[lib]
name = "aho_corasearch_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.0"
daachorse = "1.0.0"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
